version: 2
registries:
  git-github-com:
    type: git
    url: https://github.com
    username: BetaLayoutUser
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Dublin
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
  registries:
  - git-github-com
